name: Generate Combined Providers File

on:
    push:
        branches: [main]
        paths:
            - "providers/**"
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Generate Combined File
              run: |
                  echo "[" > providers.json
                  first=true
                  for f in providers/*.json; do
                    if [ "$first" = true ]; then
                      first=false
                    else
                      echo "," >> providers.json
                    fi
                    cat "$f" >> providers.json
                  done
                  echo "]" >> providers.json

            - name: Validate JSON
              run: |
                  cat providers.json | jq '.' > /dev/null

            - name: Commit and Push
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Auto-generate providers.json"
                  file_pattern: "providers.json"
                  branch: main
